pipeline {
    agent any /*{
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }*/
    
    def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/jglick/simple-maven-project-with-tests.git'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      mvnHome = tool 'Maven3'
   }
    stages {
        stage('Build') {
            steps {
                sh "'${mvnHome}/bin/mvn' -B -DskipTests clean package"
            }
        }
        stage('Test') {
            steps {
                sh "'${mvnHome}/bin/mvn' test"
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
               /* sh './jenkins/scripts/deliver.sh' */
                sh 'echo Delivered package'
            }
        }
    }
}
