pipeline {
    agent any /*{
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }*/
    tools { 
        maven 'Maven3' 
        //jdk 'jdk8' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh "'${mvnHome}/bin/mvn' test"
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
               /* sh './jenkins/scripts/deliver.sh' */
                sh 'echo Delivered package'
            }
        }
    }
}
